### PR TITLE
Fix account notification email language

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks. I guess the method exists calls can be removed.

**Comment by laoneo** [comment]
Why is this all of the sudden needed? All I did was changing $this->app to $this->getApplication(), so it basically should be the same as before.

**Comment by joomdonation** [comment]
> Thanks. I guess the method exists calls can be removed

The `loadLanguage` method is not available in all kind of applications, so it would be safe to leave it there. I can remove it if you want

> Why is this all of the sudden needed? All I did was changing $this->app to $this->getApplication(), so it basically should be the same as before

It is not the same as before. Please look at https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Plugin/CMSPlugin.php#L168 . Before, we did not pass application to plugin, so the language file is loaded base on global language. With application object passed to plugin, it will now load the language file to the application language, so there is a difference.

**Comment by laoneo** [comment]
Ok, thanks!

**Pull request merged**
