### PR TITLE
[CMS PR 40147] Use script.php to uninstall the plugin

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for https://github.com/joomla/joomla-cms/pull/40147 .

### Summary of Changes

Use the new function introduced with https://github.com/joomla/joomla-cms/pull/40768 instead of the update SQL script for uninstalling the obsolete plugin and removing its tasks on update.

The update SQL script is still used for removing the task(s).

### Testing Instructions

Code review, or update a 4.4-dev nightly build or 5.0.0-alpha1 to a 5.0-dev update package which contains the changes from here and from the CMS PR.

### CODE REVIEW

**Comment by richard67** [comment]
Unfortunately the `$data` parameter is not used in the migration method in this special case here. Tools like e.g. Phan might complain about this. @laoneo Is this a problem and can it be circumvented somehow?

**Comment by HLeithner** [comment]
I think this pr makes not much sense migrating the sql to the migrate function, we use sql to delete extensions content, we should use the migration function only if we really need it for migration. if sql is possible keep it in sql.

**Comment by richard67** [comment]
> I think this pr makes not much sense migrating the sql to the migrate function, we use sql to delete extensions content, we should use the migration function only if we really need it for migration. if sql is possible keep it in sql.

@HLeithner You mean completely not use this PR here? Or only revert this commit https://github.com/Digital-Peak/joomla-cms/pull/30/commits/e68037dc313ce8c7ef4a45031368b86b6dc167f4 for using script.php to delete the old tasks?

**Comment by HLeithner** [comment]
yes I mean the commit which move the removal from the sql file to the script.php

**Comment by richard67** [comment]
@HLeithner Done.

**Comment by laoneo** [comment]
Thanks @richard67, good work!

**Pull request merged**
